# Generated by Django 5.2.1 on 2025-05-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_servicebooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='email',
            field=models.EmailField(default='default@example.com', help_text='Email of the user at the time of booking.', max_length=254),
            preserve_default=False,
        ),
    ]
