# Generated by Django 5.2.1 on 2025-06-30 13:58

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_servicebooking_ticket_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebooking',
            name='ticket_id',
            field=models.CharField(
                max_length=12,
                blank=True,
                null=True,  # ✅ This is the missing piece
                unique=True,
            ),
        ),
    ]