# Generated by Django 5.2.1 on 2025-06-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_servicebooking_ticket_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebooking',
            name='ticket_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
