# Generated by Django 5.2.1 on 2025-06-30 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_fill_ticket_ids'),
        ('api', '0007_alter_servicebooking_ticket_id'),
    ]

    operations = [
    ]
